services:
  order:
    build: .
    container_name: order
    environment:
      - SERVER_PORT=8181
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8181:8181"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true